export const HeadTeamData = [
    {
        image: 'https://i.imgur.com/ghPprwc.jpeg',
        name: "Arghya Kamal Das",
        position: "President",
        linkedin: "https://www.linkedin.com/in/arghya-kamal-das-aa8173235/",
        instagram: "https://www.instagram.com/_ki_ar_bolbo_/",
    },
    {
        image: 'https://i.imgur.com/OxVjHNN.jpeg',
        name: "Praveen Thota",
        position: "Vice President",
        linkedin: "https://www.linkedin.com/in/praveen-t-v-n-s-5393ab223/",
        instagram: "https://www.instagram.com/p_r_a_v_e_e_n_t_h_o_t_a/",
    },
    {
        image: 'https://i.imgur.com/wr9UVwf.jpeg',
        name: "Harshit Loyalka",
        position: "General Secretary",
        linkedin: "https://www.linkedin.com/in/harshit-loyalka-80b208210/",
        instagram: "https://www.instagram.com/harshit24_loyalka/",
    }
];

export const FinalTeamData = [
    {
        image: 'https://i.imgur.com/QfHiQYi.jpeg',
        name: "Devansh Gupta",
        position: "Treasurer",
        linkedin: "https://www.linkedin.com/in/devansh-gupta-b3465822b/",
        instagram: "https://www.instagram.com/devanshg.11/",
    },
    {
        image: 'https://i.imgur.com/V9EJ1kt.jpeg',
        name: "Dona Roy",
        position: "Sponsership Head",
        linkedin: "https://www.linkedin.com/in/dona-roy-116417241/",
        instagram: "https://www.instagram.com/_.dona_roy_/",
    },
    {
        image: 'https://i.imgur.com/FhllDUR.jpeg',
        name: "Utkarsh Kumar",
        position: "Event Head",
        linkedin: "https://www.linkedin.com/in/utkarsh-kumar29/",
        instagram: "https://www.instagram.com/utkarsh9652/",
    },
    {
        image: 'https://i.imgur.com/oQ1PQF0.jpeg',
        name: "Nandan Kumar Shaw",
        position: "Tech Head",
        linkedin: "https://www.linkedin.com/in/nandan-shaw-84b509241/",
        instagram: "https://www.instagram.com/nandanshaw02/",
    },
    {
        image: 'https://i.imgur.com/H1fcxmI.jpeg',
        name: "Rakesh Gunta",
        position: "WebDev Head",
        linkedin: "https://www.linkedin.com/in/rakesh-gunta-05204a259/",
        instagram: "https://www.linkedin.com/in/rakesh-gunta-05204a259/",
    },
    {
        image: 'https://i.imgur.com/4MqJh4u.jpeg',
        name: "Upawal Murmu",
        position: "Alumni Head",
        linkedin: "https://www.linkedin.com/in/upawal-murmu-a36920241/",
        instagram: "https://www.instagram.com/upawal_here/",
    },
    {
        image: 'https://i.imgur.com/uVT3yxw.jpeg',
        name: "Shreya Dey Sarkar",
        position: "Design Head",
        linkedin: "https://www.linkedin.com/in/shreya-dey-sarkar-057421226/",
        instagram: "https://www.instagram.com/shreya4_444/",
    },
    {
        image: 'https://i.imgur.com/FIkai5u.jpeg',
        name: "Ranbir Marandi",
        position: "Senior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/ranbir-marandi-95660917b/",
        instagram: "https://www.instagram.com/ranbirmarandi/",
    },
    {
        image: 'https://i.imgur.com/IkjZpke.jpeg',
        name: "Likita",
        position: "Senior Co-ordinator",
        linkedin: "#",
        instagram: "#",
    },
    {
        image: 'https://i.imgur.com/OwIZ9Z2.jpeg',
        name: "Shaik Altaf Hussain",
        position: "Senior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/altaf434/",
        instagram: "https://www.instagram.com/shaikaltaf771/",
    },
    {
        image: 'https://i.imgur.com/xU6AWQg.jpeg',
        name: "Subham Ghosh",
        position: "Senior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/subham-ghosh-4b8a29235/",
        instagram: "https://www.instagram.com/subhamghosh_24/",
    },
    {
        image: 'https://i.imgur.com/26Njaf4.jpeg',
        name: "Bablu Asish",
        position: "Senior Co-ordinator",
        linkedin: "#",
        instagram: "#",
    }
];

export const PrefinalTeamData = [
    {
        image: 'https://i.imgur.com/b5Q1LZE.jpeg',
        name: "Animesh Punetha",
        position: "Senior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/animesh-punetha-4a04141a0/",
        instagram: "https://www.instagram.com/animesh_punetha01/",
    },
    {
        image: 'https://i.imgur.com/Nd07Adu.jpeg',
        name: "Anisha Kumari",
        position: "Senior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/anisha-kumari-222826261/",
        instagram: "https://www.instagram.com/anishakri35/",
    },
    {
        image: 'https://i.imgur.com/GlTWXrv.jpeg',
        name: "Dhritishree Saha",
        position: "Senior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/dhritishree-saha-86304624b/",
        instagram: "https://www.instagram.com/dhritis.exe/",
    },
    {
        image: 'https://i.imgur.com/pFrMgiQ.jpeg',
        name: "Jayesh Toshniwal",
        position: "Senior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/jayesh-toshniwal/",
        instagram: "https://www.instagram.com/toshniwal.jayesh/",
    },
    {
        image: 'https://i.imgur.com/MIppZY2.jpeg',
        name: "Manas Mahata",
        position: "Senior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/manas-mahato-225aa5266/",
        instagram: "https://www.instagram.com/_hllo_im_manas_/",
    },
    {
        image: 'https://i.imgur.com/Len0vyv.jpeg',
        name: "Mohammed Asif",
        position: "Senior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/md-asif-22891a264/",
        instagram: "https://www.instagram.com/better_call_asif_/",
    },
    {
        image: 'https://i.imgur.com/Hv5LggV.jpeg',
        name: "R Charisma Alex",
        position: "Senior Co-ordinator",
        linkedin: "#",
        instagram: "#",
    },
    {
        image: 'https://i.imgur.com/XVgU9JD.jpeg',
        name: "Sagnik Dutta",
        position: "Senior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/sagnik-dutta-5a0562265/",
        instagram: "https://www.instagram.com/sagnikd_30/",
    },

    {
        image: 'https://i.imgur.com/hSdjo7c.jpeg',
        name: "Sarmistha Naskar",
        position: "Senior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/sarmistha-naskar-004a38269/",
        instagram: "https://www.instagram.com/sarmistha_n12/",
    },
    {
        image: 'https://i.imgur.com/0JnVXuO.jpeg',
        name: "Soumyadeep Chakraborty",
        position: "Senior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/soumyadeep-chakraborty-716752277/",
        instagram: "https://www.instagram.com/cty_sdeep/",
    },
    {
        image: 'https://i.imgur.com/WaBLzde.jpeg',
        name: "Tanushri Ghosh",
        position: "Senior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/tanushri-ghosh-5b1814282/",
        instagram: "https://www.instagram.com/tanushriighosh/",
    },
    {
        image: 'https://i.imgur.com/ECoK8VO.jpeg',
        name: "Tina Ghosh",
        position: "Senior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/tina-ghosh-7957ba27b/",
        instagram: "https://www.instagram.com/_tina_i_am/",
    },
    {
        image: 'https://i.imgur.com/wa5nP9m.jpeg',
        name: "Vipin Sharma",
        position: "Senior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/vipin-sharma-2976b8271/",
        instagram: "https://www.instagram.com/vpn.1211/",
    }
];

export const SecondYearTeamData = [
    {
        image: 'https://i.imgur.com/rS4Fy7b.jpeg',
        name: "Abir Dutta",
        position: "Junior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/abir-dutta-14b0a82a9/",
        instagram: "#",
    },
    {
        image: 'https://i.imgur.com/dD0QK8W.jpeg',
        name: "Arnav Gupta",
        position: "Junior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/arnav-gupta-b94068296/",
        instagram: "https://www.instagram.com/guptaaarnavv/",
    },
    {
        image: 'https://i.imgur.com/IqpD9OR.jpeg',
        name: "Ayush Gupta",
        position: "Junior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/ayush-gupta-6610b5287/",
        instagram: "https://www.instagram.com/wolfofdalalst19/",
    },
    {
        image: 'https://i.imgur.com/5LqtRcG.jpeg',
        name: "Binayak Dey",
        position: "Junior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/binayak-dey-a4b36828a/",
        instagram: "https://www.instagram.com/vnayakde/",
    },
    {
        image: 'https://i.imgur.com/UBlfmhw.jpeg',
        name: "Deepika Reddy",
        position: "Junior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/deepika-reddy-dandolu-5191b32ab/",
        instagram: "https://www.instagram.com/hiihellooitsmeh/",
    },
    {
        image: 'https://i.imgur.com/2EMm4RE.jpeg',
        name: "Esha Jha",
        position: "Junior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/esha-jha-657276221/",
        instagram: "https://www.instagram.com/eshaa_jhaa/",
    },
    {
        image: 'https://i.imgur.com/g3rpc9b.jpeg',
        name: "Jishu Mapdar",
        position: "Junior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/jishu-mapdar-4b7183247/",
        instagram: "https://www.instagram.com/echoing_subcon/",
    },
    {
        image: 'https://i.imgur.com/ycTtc8m.jpeg',
        name: "Malay Roy",
        position: "Junior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/malay-roy-14706b307/",
        instagram: "https://www.instagram.com/malay_ichigo/",
    },
    {
        image: 'https://i.imgur.com/Qz0SS3t.jpeg',
        name: "Pradipto Narayan Pal",
        position: "Junior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/pradipta-pal-66a38a284/",
        instagram: "https://www.instagram.com/pradipto______/",
    },
    {
        image: 'https://i.imgur.com/42ijY4P.jpeg',
        name: "Priyankori Saha",
        position: "Junior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/priyankori-saha-818306329/",
        instagram: "https://www.instagram.com/priyankori_saha/",
    },
    {
        image: 'https://i.imgur.com/75x4rYV.jpeg',
        name: "Pynda Nanda Gopal",
        position: "Junior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/pynda-nanda-gopal-428b65320/",
        instagram: "https://www.instagram.com/nandagopal__pynda/",
    },
    {
        image: 'https://i.imgur.com/potv6az.jpeg',
        name: "Rishi Sai Teja",
        position: "Junior Co-ordinator",
        linkedin: "#",
        instagram: "https://www.instagram.com/rishisaiteja/",
    },
    {
        image: 'https://i.imgur.com/Ii995qh.jpeg',
        name: "Subhankar Maiti",
        position: "Junior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/subhankar-maiti-933785280/",
        instagram: "https://www.instagram.com/maitisubhankar55/",
    },
    {
        image: 'https://i.imgur.com/ip2gLsD.jpeg',
        name: "Suryashish Saha",
        position: "Junior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/suryashish-saha-09b8862b3/",
        instagram: "https://www.instagram.com/blessings.from.the.sun/",
    },
    {
        image: 'https://i.imgur.com/2lmglJ7.jpeg',
        name: "Triparno Chakrabarty",
        position: "Junior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/triparno-chakrabarty-114189281/",
        instagram: "https://www.instagram.com/triparno7/",
    },
    {
        image: 'https://i.imgur.com/QZf58ha.jpeg',
        name: "Varsha Verma",
        position: "Junior Co-ordinator",
        linkedin: "https://www.linkedin.com/in/varsha-verma-aa96b1241/",
        instagram: "https://www.instagram.com/varshaverma2204/",
    },
];
