export const TeamDataHome = [
    {
        image: 'https://i.imgur.com/ghPprwc.jpeg',
        name: "Arghya Kamal Das",
        position: "President",
        facebook: "#",
        linkedin: "#",
        instagram: "#",
    },
    {
        image: 'https://i.imgur.com/OxVjHNN.jpeg',
        name: "Praveen Thota",
        position: "Vice President",
        facebook: "#",
        linkedin: "#",
        instagram: "#",
    },
    {
        image: 'https://i.imgur.com/wr9UVwf.jpeg',
        name: "Harshit Loyalka",
        position: "General Secretary",
        facebook: "#",
        linkedin: "#",
        instagram: "#",
    },
    {
        image: 'https://i.imgur.com/QfHiQYi.jpeg',
        name: "Devansh Gupta",
        position: "Treasurer",
        facebook: "#",
        linkedin: "#",
        instagram: "#",
    },
    {
        image: 'https://i.imgur.com/V9EJ1kt.jpeg',
        name: "Dona Roy",
        position: "Sponsership Head",
        facebook: "#",
        linkedin: "#",
        instagram: "#",
    },
    {
        image: 'https://i.imgur.com/FhllDUR.jpeg',
        name: "Utkarsh Kumar",
        position: "Event Head",
        facebook: "#",
        linkedin: "#",
        instagram: "#",
    },
    {
        image: 'https://i.imgur.com/oQ1PQF0.jpeg',
        name: "Nandan Kumar Shaw",
        position: "Tech Head",
        facebook: "#",
        linkedin: "#",
        instagram: "#",
    },
    {
        image: 'https://i.imgur.com/H1fcxmI.jpeg',
        name: "Rakesh Gunta",
        position: "WebDev Head",
        facebook: "#",
        linkedin: "#",
        instagram: "#",
    },
    {
        image: 'https://i.imgur.com/4MqJh4u.jpeg',
        name: "Upawal Murmu",
        position: "Alumni Head",
        facebook: "#",
        linkedin: "#",
        instagram: "#",
    },
    {
        image: 'https://i.imgur.com/uVT3yxw.jpeg',
        name: "Shreya Dey Sarkar",
        position: "Design Head",
        facebook: "#",
        linkedin: "#",
        instagram: "#",
    },
    {
        image: 'https://i.imgur.com/FIkai5u.jpeg',
        name: "Ranbir Marandi",
        position: "Senior Co-ordinator",
        facebook: "#",
        linkedin: "#",
        instagram: "#",
    },
    {
        image: 'https://i.imgur.com/IkjZpke.jpeg',
        name: "Likita",
        position: "Senior Co-ordinator",
        facebook: "#",
        linkedin: "#",
        instagram: "#",
    },
    {
        image: 'https://i.imgur.com/OwIZ9Z2.jpeg',
        name: "Shaik Altaf Hussain",
        position: "Senior Co-ordinator",
        facebook: "#",
        linkedin: "#",
        instagram: "#",
    },
    {
        image: 'https://i.imgur.com/xU6AWQg.jpeg',
        name: "Subham Ghosh",
        position: "Senior Co-ordinator",
        facebook: "#",
        linkedin: "#",
        instagram: "#",
    },
    {
        image: 'https://i.imgur.com/26Njaf4.jpeg',
        name: "Bablu Asish",
        position: "Senior Co-ordinator",
        facebook: "#",
        linkedin: "#",
        instagram: "#",
    }
]